[project]
name = "personal-page"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.2",
    "jinja2>=3.1.6",
    "python-multipart>=0.0.20",
    "uvicorn>=0.38.0",
]
